DROP TABLE IF EXISTS games;
DROP TABLE IF EXISTS deposits;
DROP TABLE IF EXISTS tokens;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
   id INT GENERATED ALWAYS AS IDENTITY,
   username CHAR(32) NOT NULL UNIQUE,
   password CHAR(32) NOT NULL,
   balance INT NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(id)
);

CREATE TABLE tokens(
   id INT GENERATED ALWAYS AS IDENTITY,
   user_id INT NOT NULL UNIQUE,
   token VARCHAR(255) NOT NULL UNIQUE,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(id),
   CONSTRAINT user_token
      FOREIGN KEY(user_id) 
	  REFERENCES users(id)
);

CREATE TABLE deposits(
   id INT GENERATED ALWAYS AS IDENTITY,
   user_id INT NOT NULL,
   amount INT NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(id),
   CONSTRAINT user_deposit
      FOREIGN KEY(user_id) 
	  REFERENCES users(id)
);

CREATE TABLE games(
   id INT GENERATED ALWAYS AS IDENTITY,
   creator_id INT NOT NULL,
   name CHAR(32) NOT NULL UNIQUE,
   title CHAR(32) NOT NULL,
   price INT NOT NULL,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   deleted_at TIMESTAMP,
   PRIMARY KEY(id),
   CONSTRAINT user_games
      FOREIGN KEY(creator_id) 
	  REFERENCES users(id)
);
